// Package index generates the committed .agent/index.md (D029).
package index

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cinch/internal/manifest"
)

// D029: the index is a committed generated file. Its one-line descriptions come
// from each file's H1 (or first non-empty line), which a bare `ls -R` loses.

const indexHeader = "# Doc index\n\n<!-- generated by cinch — run `cinch index`; do not edit -->\n\n"

var indexSkip = map[string]bool{
	"index.md": true,
	"analysis": true,
	"plans":    true,
	"events":   true,
}

func IndexPath(root string) string { return filepath.Join(manifest.AgentDir(root), "index.md") }

func firstHeading(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	text := string(b)
	// Leading --- ... --- is YAML front-matter (D010 owns: lists), not content.
	// Skip it so the H1 below becomes the index entry.
	if strings.HasPrefix(text, "---\n") {
		if end := strings.Index(text[4:], "\n---"); end >= 0 {
			text = text[4+end+5:] // 5 = len("\n---\n")
		}
	}
	for _, line := range strings.Split(text, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "<!--") {
			continue
		}
		return strings.TrimSpace(strings.TrimLeft(t, "# "))
	}
	return ""
}

// BuildIndex renders the index content in memory.
func BuildIndex(root string) (string, error) {
	adir := manifest.AgentDir(root)
	var lines []string

	err := filepath.WalkDir(adir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(adir, p)
		if rel == "." {
			return nil
		}
		top := strings.SplitN(rel, string(filepath.Separator), 2)[0]
		if indexSkip[top] || indexSkip[rel] {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".md") {
			return nil
		}
		lines = append(lines, fmt.Sprintf("- `%s` — %s", rel, firstHeading(p)))
		return nil
	})
	if err != nil {
		return "", err
	}

	sort.Strings(lines)
	return indexHeader + strings.Join(lines, "\n") + "\n", nil
}

// Run implements `cinch index`.
func Run(root string) error {
	content, err := BuildIndex(root)
	if err != nil {
		return err
	}
	if err := os.WriteFile(IndexPath(root), []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote .agent/index.md (%d entries)\n",
		strings.Count(content, "\n- `")+strings.Count(content, "\n\n- `"))
	return nil
}
