package cinch

import (
	"reflect"
	"strings"
	"testing"
)

func TestHeader(t *testing.T) {
	t.Run("markdown", func(t *testing.T) {
		h := header("templates/x.md", "body", styleMarkdown)
		if !strings.HasPrefix(h, "<!-- generated by cinch from templates/x.md") || !strings.HasSuffix(h, "-->\n\n") {
			t.Fatalf("header = %q", h)
		}
	})

	t.Run("shell", func(t *testing.T) {
		h := header("templates/x.sh", "body", styleShell)
		if !strings.HasPrefix(h, "#!/bin/sh\n# generated by cinch") || !strings.HasSuffix(h, "\n\n") {
			t.Fatalf("header = %q", h)
		}
	})

	t.Run("body hash embedded", func(t *testing.T) {
		h := header("templates/x.md", "body", styleMarkdown)
		if !strings.Contains(h, bodyHash("body")) {
			t.Fatalf("header %q does not contain body-sha %s", h, bodyHash("body"))
		}
	})
}

func TestBodyHash(t *testing.T) {
	a := bodyHash("x")
	b := bodyHash("x")
	if a != b {
		t.Fatal("bodyHash not deterministic")
	}
	if bodyHash("x") == bodyHash("y") {
		t.Fatal("bodyHash collides for different input")
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	cases := []struct {
		name string
		data string
		want bool
	}{
		{"markdown header", "<!-- generated by cinch from x -- do not edit -->\n\nbody", true},
		{"shell header", "#!/bin/sh\n# generated by cinch from x -- do not edit\n\nbody", true},
		{"second line only", "body\n<!-- generated by cinch -->\n", true},
		{"third line only", "a\nb\n<!-- generated by cinch -->\n", false},
		{"plain", "plain text\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasGeneratedHeader(tc.data); got != tc.want {
				t.Fatalf("hasGeneratedHeader = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestTitleAndTrigger(t *testing.T) {
	cases := []struct {
		name        string
		body        string
		wantTitle   string
		wantTrigger string
	}{
		{"no h1", "plain text\n", "", ""},
		{"title only", "# T", "T", ""},
		{"basic", "# Title\nRun the thing.", "Title", "Run the thing."},
		{"no punctuation", "# Title\na\nb", "Title", "a b"},
		{"blank lines after title", "# Title\n\n\nRun it.\n", "Title", "Run it."},
		{"paragraph break ends trigger", "# Title\na\n\nb", "Title", "a"},
		{"sentence end", "# Title\nFirst sentence.\nSecond.", "Title", "First sentence."},
		{"heading breaks trigger", "# Title\nintro\n## Sub\nmore", "Title", "intro"},
		{"list breaks trigger", "# Title\nintro\n- item", "Title", "intro"},
		{"code fence breaks trigger", "# Title\nintro\n```\ncode\n```", "Title", "intro"},
		{"numbered list breaks trigger", "# Title\nintro\n1. item", "Title", "intro"},
		{"crlf", "# Title\r\nRun it.\r\n", "Title", "Run it."},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			title, trigger := titleAndTrigger(tc.body)
			if title != tc.wantTitle || trigger != tc.wantTrigger {
				t.Fatalf("titleAndTrigger = (%q, %q), want (%q, %q)", title, trigger, tc.wantTitle, tc.wantTrigger)
			}
		})
	}
}

func TestParseFrontmatterAbsent(t *testing.T) {
	got, err := parseFrontmatter([]byte("# Title\n\nno frontmatter here\n"))
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	if !reflect.DeepEqual(got, docFrontmatter{}) {
		t.Fatalf("got = %+v, want zero value", got)
	}
}

func TestParseFrontmatterOwnsAndPrefix(t *testing.T) {
	body := "---\nowns:\n  - internal/cinch\n  - main.go\nrule_prefix: SIG-\n---\n# Title\n\nbody\n"
	got, err := parseFrontmatter([]byte(body))
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	want := docFrontmatter{Owns: []string{"internal/cinch", "main.go"}, RulePrefix: "SIG-"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got = %+v, want %+v", got, want)
	}
}

func TestParseFrontmatterUnterminated(t *testing.T) {
	body := "---\nowns:\n  - internal/cinch\n\n# Title, no closing fence\n"
	got, err := parseFrontmatter([]byte(body))
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	if !reflect.DeepEqual(got, docFrontmatter{}) {
		t.Fatalf("got = %+v, want zero value for an unterminated block", got)
	}
}

func TestParseFrontmatterMalformedYAML(t *testing.T) {
	body := "---\nowns: \"not-a-list\"\n---\n# Title\n"
	_, err := parseFrontmatter([]byte(body))
	if err == nil {
		t.Fatal("err = nil, want an error for owns: given as a scalar instead of a list")
	}
}

func TestParseFrontmatterFileMissing(t *testing.T) {
	_, err := parseFrontmatterFile("/nonexistent/path/does-not-exist.md")
	if err == nil {
		t.Fatal("err = nil, want an error for a missing file")
	}
}

func TestParseFrontmatterFileRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := writeTestFile(t, dir, "domain.md", "---\nrule_prefix: SIG-\n---\n# Signatures\n")
	got, err := parseFrontmatterFile(path)
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	if got.RulePrefix != "SIG-" {
		t.Fatalf("RulePrefix = %q, want %q", got.RulePrefix, "SIG-")
	}
}
