package cinch

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"cinch/internal/gitutil"

	"gopkg.in/yaml.v3"
)

const headerPrefix = "generated by cinch"

type fileStyle int

const (
	styleMarkdown fileStyle = iota
	styleShell
)

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

func header(source, body string, style fileStyle) string {
	marker := fmt.Sprintf("%s from %s — do not edit; body-sha: %s", headerPrefix, source, bodyHash(body))
	if style == styleShell {
		return "#!/bin/sh\n# " + marker + "\n\n"
	}
	return "<!-- " + marker + " -->\n\n"
}

func hasGeneratedHeader(data string) bool {
	lines := strings.SplitN(data, "\n", 3)
	for i := 0; i < len(lines) && i < 2; i++ {
		if strings.Contains(lines[i], headerPrefix) {
			return true
		}
	}
	return false
}

const (
	pathsDocsKey     = "paths.docs"
	defaultDocsPath  = ".docs"
	pathsHooksKey    = "paths.hooks"
	defaultHooksPath = ".githooks"
	pathsExcludeKey  = "paths.exclude"
)

func docsPathValue(m *manifest) string {
	return manifestVar(m, pathsDocsKey, defaultDocsPath)
}

func hooksPathValue(m *manifest) string {
	return manifestVar(m, pathsHooksKey, defaultHooksPath)
}

func ResolveDocsRoot(root string) (string, error) {
	m, err := loadManifestOptional(root)
	if err != nil {
		return "", err
	}
	return filepath.Join(root, docsPathValue(m)), nil
}

func titleAndTrigger(body string) (title, trigger string) {
	lines := strings.Split(body, "\n")
	titleIdx := -1
	for i, l := range lines {
		if t, ok := strings.CutPrefix(l, "# "); ok {
			title = strings.TrimSpace(t)
			titleIdx = i
			break
		}
	}
	if titleIdx == -1 {
		return "", ""
	}

	var parts []string
	for _, l := range lines[titleIdx+1:] {
		line := strings.TrimSpace(l)
		if line == "" {
			if len(parts) > 0 {
				break
			}
			continue
		}
		if len(parts) > 0 && startsNewBlock(line) {
			break
		}
		parts = append(parts, line)
		if endsSentence(line) {
			break
		}
	}
	trigger = strings.Join(parts, " ")
	return title, trigger
}

func startsNewBlock(line string) bool {
	for _, prefix := range []string{"#", "-", "*", "```", "|", ">"} {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	if i := strings.IndexByte(line, '.'); i > 0 && i <= 2 {
		if _, err := strconv.Atoi(line[:i]); err == nil {
			return true
		}
	}
	return false
}

func endsSentence(line string) bool {
	if line == "" {
		return false
	}
	switch line[len(line)-1] {
	case '.', '!', '?':
		return true
	}
	return false
}

// docFrontmatter is the owns:/rule_prefix: convention documented for
// consumers in internal/cinch/docs/templates/docs-maintain-domain.md.
type docFrontmatter struct {
	Owns       []string `yaml:"owns"`
	RulePrefix string   `yaml:"rule_prefix"`
}

// parseFrontmatter extracts a leading `---`-delimited YAML block from a
// doc's content. The common case today is no frontmatter at all, and an
// absent or unterminated block returns a zero-value docFrontmatter with no
// error — only malformed YAML inside a well-delimited block is an error,
// since a typo'd block silently producing an empty Owns is a worse failure
// mode than a loud one.
func parseFrontmatter(content []byte) (docFrontmatter, error) {
	var fm docFrontmatter

	scanner := bufio.NewScanner(bytes.NewReader(content))
	if !scanner.Scan() || strings.TrimRight(scanner.Text(), "\r") != "---" {
		return fm, nil
	}

	var block bytes.Buffer
	closed := false
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimRight(line, "\r") == "---" {
			closed = true
			break
		}
		block.WriteString(line)
		block.WriteByte('\n')
	}
	if err := scanner.Err(); err != nil {
		return fm, err
	}
	if !closed {
		return docFrontmatter{}, nil
	}

	if err := yaml.Unmarshal(block.Bytes(), &fm); err != nil {
		return docFrontmatter{}, err
	}
	return fm, nil
}

func parseFrontmatterFile(path string) (docFrontmatter, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return docFrontmatter{}, err
	}
	return parseFrontmatter(data)
}

func IsGitRepo(repoRoot string) bool {
	return gitutil.IsRepo(repoRoot)
}
