package cinch

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

const headerPrefix = "generated by cinch"

type fileStyle int

const (
	styleMarkdown fileStyle = iota
	styleShell
)

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

func header(source, body string, style fileStyle) string {
	marker := fmt.Sprintf("%s from %s — do not edit; body-sha: %s", headerPrefix, source, bodyHash(body))
	if style == styleShell {
		return "#!/bin/sh\n# " + marker + "\n\n"
	}
	return "<!-- " + marker + " -->\n\n"
}

func hasGeneratedHeader(data string) bool {
	lines := strings.SplitN(data, "\n", 3)
	for i := 0; i < len(lines) && i < 2; i++ {
		if strings.Contains(lines[i], headerPrefix) {
			return true
		}
	}
	return false
}
