package cinch

import (
	"strings"
	"testing"
)

func TestHeader(t *testing.T) {
	t.Run("markdown", func(t *testing.T) {
		h := header("templates/x.md", "body", styleMarkdown)
		if !strings.HasPrefix(h, "<!-- generated by cinch from templates/x.md") || !strings.HasSuffix(h, "-->\n\n") {
			t.Fatalf("header = %q", h)
		}
	})

	t.Run("shell", func(t *testing.T) {
		h := header("templates/x.sh", "body", styleShell)
		if !strings.HasPrefix(h, "#!/bin/sh\n# generated by cinch") || !strings.HasSuffix(h, "\n\n") {
			t.Fatalf("header = %q", h)
		}
	})

	t.Run("body hash embedded", func(t *testing.T) {
		h := header("templates/x.md", "body", styleMarkdown)
		if !strings.Contains(h, bodyHash("body")) {
			t.Fatalf("header %q does not contain body-sha %s", h, bodyHash("body"))
		}
	})
}

func TestBodyHash(t *testing.T) {
	if bodyHash("x") != bodyHash("x") {
		t.Fatal("bodyHash not deterministic")
	}
	if bodyHash("x") == bodyHash("y") {
		t.Fatal("bodyHash collides for different input")
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	cases := []struct {
		name string
		data string
		want bool
	}{
		{"markdown header", "<!-- generated by cinch from x -- do not edit -->\n\nbody", true},
		{"shell header", "#!/bin/sh\n# generated by cinch from x -- do not edit\n\nbody", true},
		{"second line only", "body\n<!-- generated by cinch -->\n", true},
		{"third line only", "a\nb\n<!-- generated by cinch -->\n", false},
		{"plain", "plain text\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasGeneratedHeader(tc.data); got != tc.want {
				t.Fatalf("hasGeneratedHeader = %v, want %v", got, tc.want)
			}
		})
	}
}
