package cinch

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed philosophy.md
var philosophySrc string

//go:embed templates/rules.md
var rulesTemplateSrc string

// varRe matches {{key}} tokens. Literal substitution only — no loops, no
// conditionals, no template engine.
var varRe = regexp.MustCompile(`\{\{([a-zA-Z0-9_.-]+)\}\}`)

// substitute replaces every {{key}} in body with vars[key]. An undefined
// variable is an error, never an empty string — it returns every key it
// could not resolve so the caller can report them all at once.
func substitute(body string, vars map[string]string) (string, []string) {
	missing := map[string]bool{}
	out := varRe.ReplaceAllStringFunc(body, func(m string) string {
		key := m[2 : len(m)-2]
		if v, ok := vars[key]; ok {
			return v
		}
		missing[key] = true
		return m
	})
	return out, sortedKeys(missing)
}

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

const headerPrefix = "<!-- generated by cinch"

// header builds the generated-file header for body, stamped with source (the
// embedded template's path, e.g. "philosophy.md" or "templates/rules.md") so
// a re-render is idempotent: identical source + identical manifest always
// produces identical bytes, and a re-render diff proves tampering.
func header(source, body string) string {
	return fmt.Sprintf("%s from %s — do not edit; body-sha: %s -->\n\n", headerPrefix, source, bodyHash(body))
}

// renderFile is one output cinch render produces.
type renderFile struct {
	Dest   string // repo-relative path to write
	Source string // embedded source path, for the header
	Body   string // rendered body (post-substitution), pre-header
}

// renderAll produces every Stage 2 output in memory: philosophy copied
// verbatim (it has no variables — see philosophy.md), templates/rules.md
// substituted against the manifest.
func renderAll(m *Manifest) ([]renderFile, error) {
	rulesBody, missing := substitute(rulesTemplateSrc, m.Vars)
	if len(missing) > 0 {
		return nil, fmt.Errorf("templates/rules.md: undefined manifest variables: %s", strings.Join(missing, ", "))
	}

	return []renderFile{
		{Dest: ".agent/workflows/doc-philosophy.md", Source: "philosophy.md", Body: philosophySrc},
		{Dest: ".agent/workflows/rules.md", Source: "templates/rules.md", Body: rulesBody},
	}, nil
}

// CmdRender implements `cinch render`: writes every Stage 2 output under
// root, header-stamped. Idempotent — re-running with the same manifest and
// embedded templates produces byte-identical files, so a re-render diff
// proves tampering.
func CmdRender(root string) int {
	m, err := loadManifest(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
		return 1
	}

	files, err := renderAll(m)
	if err != nil {
		fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
		return 1
	}

	for _, f := range files {
		dst := filepath.Join(root, f.Dest)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
			return 1
		}
		content := header(f.Source, f.Body) + f.Body
		if err := os.WriteFile(dst, []byte(content), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
			return 1
		}
		fmt.Printf("rendered %s\n", f.Dest)
	}
	return 0
}
