package cinch

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

//go:embed docs/philosophy.md
var philosophySrc string

//go:embed docs/templates
var templatesFS embed.FS

const templatesDir = "docs/templates"

// varRe matches {{key}} tokens. Literal substitution only — no loops, no
// conditionals, no template engine.
var varRe = regexp.MustCompile(`\{\{([a-zA-Z0-9_.-]+)\}\}`)

// substitute replaces every {{key}} in body with vars[key]. An undefined
// variable is an error, never an empty string — it returns every key it
// could not resolve so the caller can report them all at once.
func substitute(body string, vars map[string]string) (string, []string) {
	missing := map[string]bool{}
	out := varRe.ReplaceAllStringFunc(body, func(m string) string {
		key := m[2 : len(m)-2]
		if v, ok := vars[key]; ok {
			return v
		}
		missing[key] = true
		return m
	})
	return out, sortedKeys(missing)
}

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

const headerPrefix = "<!-- generated by cinch"

// header builds the generated-file header for body, stamped with source (the
// embedded template's path, e.g. "docs/philosophy.md" or
// "docs/templates/maintain-domain.md") so a re-render is idempotent: identical
// source + identical manifest always produces identical bytes, and a
// re-render diff proves tampering.
func header(source, body string) string {
	return fmt.Sprintf("%s from %s — do not edit; body-sha: %s -->\n\n", headerPrefix, source, bodyHash(body))
}

// renderFile is one output cinch render produces.
type renderFile struct {
	Dest   string // repo-relative path to write
	Source string // embedded source path, for the header
	Body   string // rendered body (post-substitution), pre-header
}

// renderAll produces every Stage 2 output in memory: philosophy copied
// verbatim (it has no variables — see docs/philosophy.md), every
// docs/templates/*.md file substituted against the manifest, and a generated
// workflow index derived from the rendered bodies.
func renderAll(m *Manifest) ([]renderFile, error) {
	entries, err := fs.ReadDir(templatesFS, templatesDir)
	if err != nil {
		return nil, fmt.Errorf("internal: reading embedded templates: %w", err)
	}

	docsRoot := docsPathValue(m)
	workflowsDir := docsRoot + "/workflows"

	vars := map[string]string{}
	if m != nil {
		for k, v := range m.Vars {
			vars[k] = v
		}
	}
	vars[pathsDocsKey] = docsRoot

	var files []renderFile
	var errLines []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		src := templatesDir + "/" + name
		raw, err := fs.ReadFile(templatesFS, src)
		if err != nil {
			return nil, fmt.Errorf("internal: reading embedded %s: %w", src, err)
		}
		body, missing := substitute(string(raw), vars)
		if len(missing) > 0 {
			errLines = append(errLines, fmt.Sprintf("%s: undefined manifest variables: %s", src, strings.Join(missing, ", ")))
			continue
		}
		files = append(files, renderFile{Dest: workflowsDir + "/" + name, Source: src, Body: body})
	}
	if len(errLines) > 0 {
		return nil, fmt.Errorf("%s", strings.Join(errLines, "\n"))
	}

	files = append(files, renderFile{Dest: workflowsDir + "/doc-philosophy.md", Source: "docs/philosophy.md", Body: philosophySrc})

	sort.Slice(files, func(i, j int) bool { return files[i].Dest < files[j].Dest })

	files = append(files, buildIndex(files, workflowsDir))

	return files, nil
}

// buildIndex derives a trigger table from the workflow files already
// rendered — no authored content, no manifest variables. Title is a file's
// first "# " line; trigger is the first non-blank line after it. Any agent
// that reads AGENTS.md can be pointed at this one file instead of a
// per-harness skill wrapper per workflow.
func buildIndex(files []renderFile, workflowsDir string) renderFile {
	var b strings.Builder
	b.WriteString("# Workflow Index\n\n")
	b.WriteString("Generated by cinch. Read the linked file when its trigger applies.\n\n")
	b.WriteString("| Workflow | Trigger |\n")
	b.WriteString("|---|---|\n")
	for _, f := range files {
		name := filepath.Base(f.Dest)
		_, trigger := titleAndTrigger(f.Body)
		fmt.Fprintf(&b, "| [%s](%s) | %s |\n", name, name, trigger)
	}
	return renderFile{Dest: workflowsDir + "/index.md", Source: "templates/*.md", Body: b.String()}
}

// titleAndTrigger extracts a workflow's H1 title and its trigger (the first
// sentence after it — when to read the file), both verbatim. Some workflows
// hand-wrap that opening sentence across physical lines, so the trigger
// joins continuation lines until one ends in sentence punctuation, a blank
// line, or a new block (bullet, heading, fence, table, quote) — whichever
// comes first.
func titleAndTrigger(body string) (title, trigger string) {
	lines := strings.Split(body, "\n")
	titleIdx := -1
	for i, l := range lines {
		if t, ok := strings.CutPrefix(l, "# "); ok {
			title = t
			titleIdx = i
			break
		}
	}
	if titleIdx == -1 {
		return "", ""
	}

	var parts []string
	for _, l := range lines[titleIdx+1:] {
		line := strings.TrimSpace(l)
		if line == "" {
			if len(parts) > 0 {
				break
			}
			continue // blank lines before the trigger starts (e.g. under the H1)
		}
		if len(parts) > 0 && startsNewBlock(line) {
			break
		}
		parts = append(parts, line)
		if endsSentence(line) {
			break
		}
	}
	trigger = strings.Join(parts, " ")
	return title, trigger
}

// startsNewBlock reports whether line opens a new markdown block (heading,
// list item, fence, table row, blockquote) rather than continuing prose.
func startsNewBlock(line string) bool {
	for _, prefix := range []string{"#", "-", "*", "```", "|", ">"} {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	if i := strings.IndexByte(line, '.'); i > 0 && i <= 2 {
		if _, err := strconv.Atoi(line[:i]); err == nil {
			return true // ordered list item, e.g. "1. "
		}
	}
	return false
}

// endsSentence reports whether line's last character terminates a sentence.
func endsSentence(line string) bool {
	if line == "" {
		return false
	}
	switch line[len(line)-1] {
	case '.', '!', '?':
		return true
	}
	return false
}

// CmdRender implements `cinch render`: writes every Stage 2 output under
// root, header-stamped. Idempotent — re-running with the same manifest and
// embedded templates produces byte-identical files, so a re-render diff
// proves tampering.
func CmdRender(root string) int {
	m, err := loadManifest(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
		return 1
	}

	files, err := renderAll(m)
	if err != nil {
		fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
		return 1
	}

	for _, f := range files {
		dst := filepath.Join(root, f.Dest)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
			return 1
		}
		content := header(f.Source, f.Body) + f.Body
		if err := os.WriteFile(dst, []byte(content), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "cinch: "+err.Error())
			return 1
		}
		fmt.Printf("rendered %s\n", f.Dest)
	}
	return 0
}
