package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
)

// varRe matches {{key}} tokens. Literal substitution only — no loops, no
// conditionals, no template engine.
var varRe = regexp.MustCompile(`\{\{([a-zA-Z0-9_.-]+)\}\}`)

// substitute replaces every {{key}} in body with vars[key]. An undefined
// variable is an error, never an empty string — it returns every key it
// could not resolve so the caller can report them all at once.
func substitute(body string, vars map[string]string) (string, []string) {
	missing := map[string]bool{}
	out := varRe.ReplaceAllStringFunc(body, func(m string) string {
		key := m[2 : len(m)-2]
		if v, ok := vars[key]; ok {
			return v
		}
		missing[key] = true
		return m
	})
	return out, sortedKeys(missing)
}

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

const headerPrefix = "<!-- generated by cinch"

// header builds the generated-file header for body, stamped with source (the
// embedded template's path, e.g. "philosophy.md" or "templates/rules.md") so
// a re-render is idempotent: identical source + identical manifest always
// produces identical bytes, and a re-render diff proves tampering.
func header(source, body string) string {
	return fmt.Sprintf("%s from %s — do not edit; body-sha: %s -->\n\n", headerPrefix, source, bodyHash(body))
}
