package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// D005: literal substitution only — no loops, no conditionals, no template
// engine. An undefined variable is an error, not an empty string.
var varRe = regexp.MustCompile(`\{\{([a-zA-Z0-9_.-]+)\}\}`)

// D063: whole-file and fragment inclusion are file lists driven by key
// presence, not branches. Templates declare `requires:` keys in front-matter;
// a fragment is composed into its base at an anchor comment.
const fragmentDir = "fragments"

var composeRe = regexp.MustCompile(`(?m)^<!-- compose: ([a-z0-9-]+) -->[ \t]*\n`)

// parseFrontMatter splits a leading `---` delimited block off a template,
// returning the body and any `requires:` keys it declares.
func parseFrontMatter(src string) (body string, requires []string) {
	if !strings.HasPrefix(src, "---\n") {
		return src, nil
	}
	end := strings.Index(src[4:], "\n---")
	if end < 0 {
		return src, nil
	}
	fm := src[4 : 4+end]
	body = strings.TrimLeft(src[4+end+4:], "\n")
	for _, line := range strings.Split(fm, "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, "requires:"); ok {
			requires = strings.Fields(rest)
		}
	}
	return body, requires
}

// composeFragments replaces every anchor comment in base with the named
// fragment file from templates/fragments/. A fragment whose requires keys are
// absent from the manifest is skipped and its anchor removed; an anchor whose
// fragment file is missing is an authoring error.
func composeFragments(tdir, rel, base string, m *Manifest) (string, error) {
	fragDir := filepath.Join(tdir, fragmentDir)
	for {
		loc := composeRe.FindStringSubmatchIndex(base)
		if loc == nil {
			return base, nil
		}
		name := base[loc[2]:loc[3]]
		fb, err := os.ReadFile(filepath.Join(fragDir, name+".md"))
		if err != nil {
			return "", fmt.Errorf("templates/%s: anchor for missing fragment %q", rel, name)
		}
		fbody, freq := parseFrontMatter(string(fb))
		repl := ""
		if m.hasVars(freq) {
			repl = strings.TrimRight(fbody, "\n") + "\n"
		}
		base = base[:loc[0]] + repl + base[loc[1]:]
	}
}

// hasVars reports whether every key exists in the flattened variable view —
// key presence is a shape declaration (D063).
func (m *Manifest) hasVars(keys []string) bool {
	for _, k := range keys {
		if _, ok := m.Vars[k]; !ok {
			return false
		}
	}
	return true
}

const headerPrefix = "<!-- generated by cinch"

// templatesDir resolves where the portable templates live. Under the split
// (D031) they belong to the cinch install, not the consuming project.
// Resolution order: $CINCH_HOME/templates, then <dir of binary>/../templates,
// then ~/.cinch/templates. Phase 1 may replace this with go:embed.
func templatesDir(root string) string {
	if h := os.Getenv("CINCH_HOME"); h != "" {
		return filepath.Join(h, "templates")
	}
	if exe, err := os.Executable(); err == nil {
		if p := filepath.Join(filepath.Dir(exe), "..", "templates"); dirExists(p) {
			return filepath.Clean(p)
		}
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cinch", "templates")
}

func dirExists(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && fi.IsDir()
}

func workflowsDir(root string) string { return filepath.Join(agentDir(root), "workflows") }

// substitute replaces {{key}} with manifest literals. It returns every key it
// could not resolve, so the caller can report all of them at once.
func substitute(body string, vars map[string]string) (string, []string) {
	missing := map[string]bool{}
	out := varRe.ReplaceAllStringFunc(body, func(m string) string {
		key := m[2 : len(m)-2]
		if v, ok := vars[key]; ok {
			return v
		}
		missing[key] = true
		return m
	})
	return out, sortedKeys(missing)
}

func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

func header(rel, body string) string {
	return fmt.Sprintf("%s from templates/%s — do not edit; body-sha: %s -->\n\n",
		headerPrefix, rel, bodyHash(body))
}

// splitGenerated separates a rendered file into its header and body.
func splitGenerated(content string) (hdr, body string) {
	if !strings.HasPrefix(content, headerPrefix) {
		return "", content
	}
	i := strings.Index(content, "-->")
	if i < 0 {
		return "", content
	}
	hdr = content[:i+3]
	body = strings.TrimPrefix(content[i+3:], "\n\n")
	return hdr, body
}

func headerHash(hdr string) string {
	i := strings.Index(hdr, "body-sha: ")
	if i < 0 {
		return ""
	}
	return strings.TrimSpace(strings.TrimSuffix(hdr[i+len("body-sha: "):], "-->"))
}

type rendered struct {
	rel  string // path relative to templates/
	body string
}

// renderAll produces the expected output for every template, in memory.
func renderAll(root string, m *Manifest) ([]rendered, error) {
	tdir := templatesDir(root)
	if _, err := os.Stat(tdir); os.IsNotExist(err) {
		return nil, nil
	}

	var out []rendered
	err := filepath.WalkDir(tdir, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(d.Name(), ".md") {
			return err
		}
		rel, _ := filepath.Rel(tdir, p)
		if strings.HasPrefix(rel, fragmentDir+"/") {
			return nil // fragments compose into bases; never render standalone
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		body, requires := parseFrontMatter(string(b))
		if !m.hasVars(requires) {
			return nil // key absence selects the file out (D063)
		}
		body, err = composeFragments(tdir, rel, body, m)
		if err != nil {
			return err
		}
		body, missing := substitute(body, m.Vars)
		if len(missing) > 0 {
			return fmt.Errorf("templates/%s: undefined manifest variables: %s",
				rel, strings.Join(missing, ", "))
		}
		out = append(out, rendered{rel: rel, body: body})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].rel < out[j].rel })
	return out, nil
}

func cmdRender(root string) error {
	m, err := loadManifest(root)
	if err != nil {
		return err
	}
	files, err := renderAll(root, m)
	if err != nil {
		return err
	}
	for _, f := range files {
		dst := filepath.Join(workflowsDir(root), f.rel)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dst, []byte(header(f.rel, f.body)+f.body), 0o644); err != nil {
			return err
		}
		fmt.Printf("rendered workflows/%s\n", f.rel)
	}
	if len(files) == 0 {
		fmt.Println("no templates found — nothing to render")
	}
	return nil
}
