package main

// cinch version — the version bump/show script as a Go subcommand (core is
// Go; a node dependency would be wrong here).
//
// The scheme: one field per file, never grouped into a single const/struct — a dev-branch bump (minor/patch) and a
// main-branch hotfix bump happen on different branches and land in the same
// directory at the main -> dev sync merge; git's default 3-line diff context
// is wide enough that two single-line edits inside one small const block still
// overlap and conflict, while two files can never conflict. The formatted
// x.y.z[letter] string is therefore computed, never stored.
//
// The version files live next to the binary's clone: <binary-dir>/../version/.
// They are the single source of truth — nothing is compiled into the binary,
// so `cinch version show` can never go stale after a bump (D006: generated
// artifacts are committed; the hook amends them into the triggering commit).

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
)

var versionFields = []string{"major", "minor", "patch", "hotfix"}

const versionHeader = "// Code generated by cinch version — do not edit.\n\npackage version\n\n"

var versionFieldRe = regexp.MustCompile(`=\s*(\d+)`)

// versionDir resolves the version/ directory from the binary's own location:
// a built binary always sits at <clone>/bin/cinch, so ../version is the
// clone's version store regardless of the working directory or which repo
// cinch is invoked from.
func versionDir() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("locating the cinch binary: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	dir := filepath.Join(filepath.Dir(exe), "..", "version")
	if fi, err := os.Stat(dir); err != nil || !fi.IsDir() {
		return "", fmt.Errorf("version files not found at %s (build with 'make build' and run the binary from the cinch clone): %w", dir, err)
	}
	return dir, nil
}

func capitalize(field string) string {
	return string(field[0]-'a'+'A') + field[1:]
}

// hotfixLetter is bijective base-26: 0 -> (empty), 1 -> a, 26 -> z, 27 -> aa.
func hotfixLetter(n int) string {
	if n <= 0 {
		return ""
	}
	var b []byte
	for n > 0 {
		n--
		b = append([]byte{byte('a' + n%26)}, b...)
		n /= 26
	}
	return string(b)
}

func formatVersion(v map[string]int) string {
	return fmt.Sprintf("%d.%d.%d%s", v["major"], v["minor"], v["patch"], hotfixLetter(v["hotfix"]))
}

func readVersion(dir string) (map[string]int, error) {
	v := map[string]int{}
	for _, field := range versionFields {
		path := filepath.Join(dir, field+".go")
		b, err := os.ReadFile(path)
		if err != nil {
			v[field] = 0 // missing file reads as 0, matching upstream
			continue
		}
		m := versionFieldRe.FindSubmatch(b)
		if m == nil {
			return nil, fmt.Errorf("could not parse version field from %s", path)
		}
		n, err := strconv.Atoi(string(m[1]))
		if err != nil {
			return nil, fmt.Errorf("could not parse version field from %s: %w", path, err)
		}
		v[field] = n
	}
	return v, nil
}

func writeVersion(dir string, v map[string]int) error {
	for _, field := range versionFields {
		content := versionHeader + fmt.Sprintf("const %s = %d\n", capitalize(field), v[field])
		if err := os.WriteFile(filepath.Join(dir, field+".go"), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func bump(v map[string]int, typ string) map[string]int {
	next := map[string]int{}
	for k, n := range v {
		next[k] = n
	}
	switch typ {
	case "major":
		next["major"]++
		next["minor"], next["patch"], next["hotfix"] = 0, 0, 0
	case "minor":
		next["minor"]++
		next["patch"], next["hotfix"] = 0, 0
	case "patch":
		next["patch"]++
		next["hotfix"] = 0
	case "hotfix":
		next["hotfix"]++
	}
	return next
}

// cmdVersion implements `cinch version [show]` and `cinch version bump <type>`.
// Unlike render/index/check it does not need a git repository: it works off
// the binary's own clone, so a consumer can query the installed tool's version
// from anywhere.
func cmdVersion(args []string) error {
	dir, err := versionDir()
	if err != nil {
		return err
	}

	if len(args) == 0 || args[0] == "show" {
		v, err := readVersion(dir)
		if err != nil {
			return err
		}
		fmt.Println(formatVersion(v))
		return nil
	}

	if args[0] != "bump" || len(args) != 2 {
		return fmt.Errorf("usage: cinch version [show] | cinch version bump <major|minor|patch|hotfix>")
	}
	typ := args[1]
	switch typ {
	case "major", "minor", "patch", "hotfix":
	default:
		return fmt.Errorf("usage: cinch version bump <major|minor|patch|hotfix> (got %q)", typ)
	}

	cur, err := readVersion(dir)
	if err != nil {
		return err
	}
	next := bump(cur, typ)
	if err := writeVersion(dir, next); err != nil {
		return err
	}
	fmt.Printf("cinch: %s -> %s\n", formatVersion(cur), formatVersion(next))
	return nil
}
